version: '3.1'
services:
  mongo:
    image: mongo:3.5
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: thirdmadman
      MONGO_INITDB_ROOT_PASSWORD: passroot
    volumes:
      - ./mongodb:/data/db